# 文件上传绝对地址
web:
  upload-path: D:/upload/static/
# spring配置
spring:
    # 数据库配置
    datasource:
        name: finacemanage
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=true
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化大小，最小，最大
        initialSize: 1
        minIdle: 3
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #引用freemarker    
    freemarker:
      cache: false
      template-loader-path: /views/
      suffix: .html
      requestContextAttribute: request
    # 选择加载不同环境的配置文件 
    profiles: 
      active: dev
    http:
      multipart:
        #设置单个文件的大小限制
        max-file-size: 1000MB
        #设置单次请求的总大小限制
        max-request-size: 1000MB
    resources:
      static-locations: file:${web.upload-path},/static/
    # 发生404错误的时候，抛出异常
    mvc:
      #定义静态资源位置访问映射
      static-path-pattern: /static/**
      throw-exception-if-no-handler-found: true
    jmx:
      default-domain: WebFrame
      
# 配置请求头传输大小
server:
 # servlet:
   # context-path:/finacemanage
  max-http-header-size: 10000000

  
# Shiro
shiro:
  configLocation: classpath:/ehcache-shiro.xml
      
#mybatis配置
mybatis:
  configLocation: classpath:mybatis-config.xml
  mapperLocations: classpath:com/yuanwang/*/dao/*.xml
  typeAliasesPackage: com.yuanwang
  
##pagehelper:
  ##helperDialect: mysql
  ##reasonable: true
  ##supportMethodsArguments: true
  ##params:
    ##count: countSql
    
##开启ehcache缓存
cache:
  ehcache:
    config: classpath:ehcache.xml
    
##日志输出级别
logging:
  level:
     com.yuanwang.*.* : debug
